# Generated by Django 6.1.1 on 2026-09-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('width', models.FloatField(default=2.0)),
                ('height', models.FloatField(default=2.0)),
                ('depth', models.FloatField(default=2.0)),
                ('position_x', models.FloatField(default=2.0)),
                ('position_y', models.FloatField(default=2.0)),
                ('position_z', models.FloatField(default=2.0)),
            ],
        ),
    ]
